### ISSUE TITLE
[Feature] Add game server address on events

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/LogApi#1]
Hi, would be great to add server ip that get the event from. 

Example:

```
{
ServerAddress: 'IP:PORT',
Event: 'EventNamet',
UserId: UserID,
Name: 'UserName',
AuthId: 'STEAM_0:0:123456',
ClientAddress: 'IP:PORT'
}
```

Would be great if we want to handle 1+ server with same ip but diff port. 
I think can be done as cvar log_server_ip. on logapi.cfg

**Comment by SmileYzn** [comment]
Just use $_SERVER variables from PHP?

And I strongly recommend using the token to prevent malicious entry from other servers.

**Comment by SmileYzn** [comment]
EDIT:
I will start to send server information to events anyway

**Comment by yuyiken** [comment]
> Just use $_SERVER variables from PHP?
> 
> And I strongly recommend using the token to prevent malicious entry from other servers.

$_SERVER variable send server port also? or it create own por when send event as on node.js? 

I was testing on node.js and get ip and random port, so if I want to manage 2 or + servers with same ip I will have this issue. 

About a bearer token I'm looking how to implement it on node.js and I will use it.

 
> EDIT: I will start to send server information to events anyway

Okay thanks, I know that there are more methods to do what I want but It will be more clean to understand I think.

**Comment by SmileYzn** [comment]
I guess that last updated solve this :D
