### ISSUE TITLE
[Feature] Handle LOG_Console commands from MatchBot

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/LogApi#3]
What about handling log_console commands from MatchBot? 
Im looking to handle matchbot commands like kick ban etc. 
I was trying to send them as at_logged but that event wont get logged on Log Api, but on server was logging well.

**Comment by SmileYzn** [comment]
Try to put logapi before matchbot on metamod plugins

Em sáb., 2 de set. de 2023 17:09, yuyiken ***@***.***>
escreveu:

**Comment by yuyiken** [comment]
@SmileYzn Hi, now im not recieving the serveralertmessage from matchbot, and its on true on events.json

Any idea what can be the problem? I changed the kick message instead of LOG_CONSOLE to ALERT,

And you can see in image that its logging on console, but dont know why its not recieving by LogApi. 

![image](https://github.com/SmileYzn/LogApi/assets/74840575/c0e0ca2a-3386-49f3-96c7-c35a28b1a807)
![image](https://github.com/SmileYzn/LogApi/assets/74840575/ec03204c-a256-4fea-a6ea-620daaf7ef2d)
![image](https://github.com/SmileYzn/LogApi/assets/74840575/e14bd15a-46f8-465c-a2c1-6363c915d598)
![image](https://github.com/SmileYzn/LogApi/assets/74840575/ed8f2be4-bd45-469d-a21b-327212a2954b)
![image](https://github.com/SmileYzn/LogApi/assets/74840575/7ef2be7b-920b-4212-81f6-78b9d5f61a20)

**Comment by SmileYzn** [comment]
I wrote wrong, try to put logApi after matchbot.
If not work. I will review this to try to catch such messages. Functions
called from metamod is not really recursive in really.

Em dom., 3 de set. de 2023 05:35, yuyiken ***@***.***>
escreveu:

**Comment by yuyiken** [comment]
Tested both, LogApi before and after matchbot.

Same result.

**Comment by SmileYzn** [comment]
In such cases, we need to create an command like:

log_send_info <Informatio Data>, so server can send that custom informations to webserver.

Or just register pattern strings into log api, and when some of that patterns is reached on ServerAlertMessage log api try to catch this and send to webserver too.

The main problem that g_pfnAlertMessage is not recursive in metamod, that is the main problem here
