### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GLoOoccK** [SmileYzn/LogApi#4]
@SmileYzn

When the server is started with [Reunion 0.2.0.13](https://github.com/s1lentq/reunion), it will crash repeatedly with the following message:

free(): invalid pointer
Aborted (core dumped)
email debug.log to linux@valvesoftware.com
Thu Jun 13 08:54:40 AM -03 2024: Server restart in 10 seconds

[debug.log](https://github.com/user-attachments/files/16482271/debug.log)

This issue occurs only on Linux. It has been tested on Ubuntu 22.04 LTS and Debian 12, and works normally on Windows 10.

**Comment by SmileYzn** [comment]
Remove Reunion :+1:

**Comment by SmileYzn** [comment]
@GLoOoccK 

Try this build
https://github.com/SmileYzn/LogApi/actions/runs/10475039692

**Comment by GLoOoccK** [comment]
@SmileYzn

Thanks for trying to fix it, but it still generates the same debug.log

[debug.log](https://github.com/user-attachments/files/16679798/debug.log)

I can't say if the version of Metamod and CSSDK in the project has any relationship. I'm using it without activated AMXX plugins:

```cpp
ReHLDS version: 3.14.0.838-dev
Build date: 00:25:22 Aug 07 2024 (3770)
Build from: https://github.com/dreamstalker/rehlds/commit/7073363

ReGameDLL version: 5.28.0.737-dev
Build date: 21:56:00 Aug 16 2024
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/12f4e9b

Metamod-r v1.3.0.150, API (5:13)
Metamod-r build: 14:07:52 May  1 2024
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/cedda15

AMX Mod X 1.10.0.5467 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Jan 21 2023 20:27:33
Built from: https://github.com/alliedmodders/amxmodx/commit/27f451a
Build ID: 5467:27f451a
Core mode: JIT+ASM32
```

**Comment by GLoOoccK** [comment]
@SmileYzn

I just tested this version, and it worked fine, thanks
https://github.com/SmileYzn/LogApi/actions/runs/10476302011

**Comment by SmileYzn** [comment]
This version is not ready yet!

**Comment by SmileYzn** [comment]
Try this version:

https://github.com/SmileYzn/LogApi/actions/runs/10477910946

**Comment by GLoOoccK** [comment]
@SmileYzn

With this version it generated the following debug.log:

[debug.log](https://github.com/user-attachments/files/16681002/debug.log)

I can't say if the version of Metamod and CSSDK in the project has any relationship. I am using the following versions:

```cpp
ReHLDS version: 3.14.0.838-dev
Build date: 00:25:22 Aug 07 2024 (3770)
Build from: https://github.com/dreamstalker/rehlds/commit/7073363

ReGameDLL version: 5.28.0.737-dev
Build date: 21:56:00 Aug 16 2024
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/12f4e9b

Metamod-r v1.3.0.150, API (5:13)
Metamod-r build: 14:07:52 May  1 2024
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/cedda15

AMX Mod X 1.10.0.5467 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Jan 21 2023 20:27:33
Built from: https://github.com/alliedmodders/amxmodx/commit/27f451a
Build ID: 5467:27f451a
Core mode: JIT+ASM32
```

When you comment this part of the code:

https://github.com/SmileYzn/LogApi/blob/main/LogApi/LogApi.cpp#L33-L84

No crash occurred.

**Comment by SmileYzn** [comment]
Did you have events.cfg on logapi folder?

**Comment by GLoOoccK** [comment]
Yes

![Screenshot](https://github.com/user-attachments/assets/2c0e26a9-5171-4390-ad28-3f6eff385dc8)

**Comment by SmileYzn** [comment]
Latest fix:

https://github.com/SmileYzn/LogApi/actions/runs/10484204365

**Comment by GLoOoccK** [comment]
@SmileYzn

I tried this version, but it didn't work, I did something just to test and it worked:

```cpp
FILE* fp = fopen(LOG_API_FILE_EVENTS, "r");

if (fp)
{
	fseek(fp, 0, SEEK_END);
	long fs = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	std::string buffer(fs, '\0');
	fread(&buffer[0], 1, fs, fp);

	fclose(fp);

	auto json = nlohmann::ordered_json::parse(buffer, nullptr, true, true);

	// [...]
}
```
![de_dust2](https://github.com/user-attachments/assets/972d3526-f095-47ba-8480-7944e02808e9)

I don't know why the current code crashes, because [ReZombie](https://github.com/fl0werD/rezombie/blob/master/rezombie/src/configs/main_config.cpp#L25) has very similar code, maybe the C++ version?

**Comment by SmileYzn** [comment]
Added in current version :+1: 

Test it

**Comment by GLoOoccK** [comment]
Now it's working perfectly, thank you

**Comment by SmileYzn** [comment]
:pray:
