### ISSUE TITLE
CentOS 8 Compatibility? 

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/LogApi#6]
Hello, I was testing it on centos 8 and it gets me bad load.

Also on ubuntu loads pretty well.

![image](https://github.com/user-attachments/assets/07cbb5bf-ba22-4a18-ae39-618a5cd5ac55)

What should I take in consideration? 

Thanks.

**Comment by SmileYzn** [comment]
Need to:

- Add -dev -debug +log on to rehlds parameters
- Add debuglevel 42 on config.ini in metamod folder
- Set log on on server.cfg to make sure that server will log

To explain what is happening with logapi on CentOS 8

**Comment by yuyiken** [comment]
L 08/30/2024 - 12:25:14: [META] ERROR: dll: Failed query plugin '<logapi_mm.so>'; Couldn't open file '/cstrike/addons/logapi/dlls/logapi_mm.so': **libcurl.so.4: cannot open shared object file: No such file or directory**
L 08/30/2024 - 12:25:14: [META] ERROR: dll: Skipping plugin '<logapi_mm.so>'; couldn't query
L 08/30/2024 - 12:25:14: [META] ERROR: dll: Couldn't close plugin file 'logapi_mm.so': invalid handle
L 08/30/2024 - 12:25:14: [META] ERROR: dll: Failed to load plugin 'logapi_mm.so'

**Comment by SmileYzn** [comment]
Centos come with curl? If yes, post the


curl --version 


Output here

**Comment by yuyiken** [comment]
@SmileYzn actaully i dont have the access to system only ftp. So i cant post it. If in future if i can i will reopen it.
