### ISSUE TITLE
Server Info event task not working.

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/LogApi#7]
Hello, 

I was doing some tests and notice that Server Info event task not working after changelevel. 

When i restart server it loads and work fine but after changelevel it stops. If i send log_send_info it sends but task of autosending not works.

**Comment by yuyiken** [comment]
As you can notice in after 11:31:40 i did a changelevel and it was not working task event until 8 mins after.
Most of times its not working directly. 
server info delay is 30 sec
![event timelane](https://github.com/user-attachments/assets/6ebe9ef7-b702-45ae-9790-c5c1f715c45d)

![Captura de pantalla 2024-08-29 115544](https://github.com/user-attachments/assets/2e2f2563-0fb4-42f4-bca8-49d180ee9eb0)


![Captura de pantalla 2024-08-29 115605](https://github.com/user-attachments/assets/3d57d83a-d5f6-42f0-95e7-4967c56dcc5e)

**Comment by GLoOoccK** [comment]
Adding:

```cpp
this->m_FrameTime = 0.0f;
```

In:

https://github.com/SmileYzn/LogApi/blob/main/LogApi/LogApi.cpp#L7

```cpp
void CLogApi::ServerActivate()
{
	// [...]
}
```

This solves the issue when the map is changed, but there is still a big delay when starting the server for the first time and there must be another solution

**Comment by SmileYzn** [comment]
There is a lot of other things before event reach webserver that log api can´t control.
For tests, always test in a local webserver to make sure that is not happening.

The LogApi just sends a POST message to webserver in specified time in case of server info!

@GLoOoccK 
Set to zero is not the solution, solution is:

```this->m_FrameTime = (gpGlobals->time + this->m_log_api_delay->value);```

Not send info right after server activate, but use delay for it!

https://github.com/SmileYzn/LogApi/actions/runs/10619522704

**Comment by GLoOoccK** [comment]
@SmileYzn

It worked perfectly to change the map, it works with the right delay, but when you just turn it on, it takes on average 1 minute and 30 seconds to start the ServerInfo Event, i couldn't find the reason

**Comment by SmileYzn** [comment]
As explained, first "Event" must respect time delay after ServerActivate;
I really suspect that is not related with log api, did you tested in a local web server?

**Comment by yuyiken** [comment]
@SmileYzn Honestly no, but i will do it with old version to test it first in local. ty

This is old version, only logapi, using local webserver, server info started working after 2 mins. Will do more tests.

![image](https://github.com/user-attachments/assets/970a8bae-96cd-477e-b94e-ba63a5de47ca)

**Comment by yuyiken** [comment]
Looks like it works, I'm closing the issue. @SmileYzn what can you say about Centos?
